name: Playwright Tests

on:
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: Stg
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install API test dependencies
        run: cd api-tests && npm ci
      - name: Run API tests
        run: cd api-tests && npm test
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          API_AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: api-test-report
          path: api-tests/jest-report/
          retention-days: 30

  # ui-tests:
  #   runs-on: ubuntu-latest
  #   environment: Stg
  #   timeout-minutes: 60
  #   needs: api-tests
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*
  #     - name: Install UI test dependencies
  #       run: cd ui-tests && npm ci
  #     - name: Install Playwright Browsers
  #       run: cd ui-tests && npx playwright install --with-deps
  #     - name: Run UI tests
  #       run: cd ui-tests && npm test
  #       env:
  #         BASE_URL: ${{ vars.BASE_URL }}
  #         API_AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
  #     - uses: actions/upload-artifact@v4
  #       if: ${{ !cancelled() }}
  #       with:
  #         name: ui-test-report
  #         path: ui-tests/report/
  #         retention-days: 30
